import { state } from "./state.js";

let actx=null,master=null;
export function ac(){if(!actx){try{actx=new (window.AudioContext||window.webkitAudioContext)();master=actx.createGain();master.gain.value=state.s.muted?0:0.85;master.connect(actx.destination);}catch(e){return null;}}if(actx.state==="suspended")actx.resume();return actx;}
export function applyMute(){if(master)master.gain.value=state.s.muted?0:0.85;}
export function pok(pitch){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const pm=pitch||1;
  const o=c.createOscillator();o.type="sine";o.frequency.setValueAtTime(360*pm,t);o.frequency.exponentialRampToValueAtTime(190*pm,t+0.035);const g=c.createGain();g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.5,t+0.003);g.gain.exponentialRampToValueAtTime(0.0001,t+0.09);o.connect(g).connect(master);o.start(t);o.stop(t+0.1);
  const o2=c.createOscillator();o2.type="sine";o2.frequency.value=120*pm;const g2=c.createGain();g2.gain.setValueAtTime(0.0001,t);g2.gain.exponentialRampToValueAtTime(0.2,t+0.004);g2.gain.exponentialRampToValueAtTime(0.0001,t+0.08);o2.connect(g2).connect(master);o2.start(t);o2.stop(t+0.09);
  const len=Math.floor(c.sampleRate*0.016),nb=c.createBuffer(1,len,c.sampleRate),d=nb.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const ns=c.createBufferSource();ns.buffer=nb;const bp=c.createBiquadFilter();bp.type="bandpass";bp.frequency.value=1900*pm;bp.Q.value=1.4;const ng=c.createGain();ng.gain.setValueAtTime(0.36,t);ng.gain.exponentialRampToValueAtTime(0.0001,t+0.016);ns.connect(bp).connect(ng).connect(master);ns.start(t);ns.stop(t+0.016);}
export function bong(low){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const base=low?150:300,dur=low?2.6:1.9;const m=c.createGain();m.gain.setValueAtTime(0.55,t);m.gain.exponentialRampToValueAtTime(0.0001,t+dur);m.connect(master);[[1,1],[2.0,0.55],[2.76,0.38],[3.5,0.22],[5.4,0.12]].forEach(([p,g])=>{const o=c.createOscillator();o.type="sine";o.frequency.value=base*p;const gg=c.createGain();gg.gain.value=g;o.connect(gg).connect(m);o.start(t);o.stop(t+dur);});}
export function chime(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;[660,880,1320].forEach((f,i)=>{const o=c.createOscillator();o.type="sine";o.frequency.value=f;const g=c.createGain();const st=t+i*0.06;g.gain.setValueAtTime(0.0001,st);g.gain.exponentialRampToValueAtTime(0.3,st+0.01);g.gain.exponentialRampToValueAtTime(0.0001,st+0.3);o.connect(g).connect(master);o.start(st);o.stop(st+0.3);});}
export function fanfare(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const notes=[523.25,659.25,783.99,1046.5];
  notes.forEach((f,i)=>{const st=t+i*0.075;[1,2].forEach((h,hi)=>{const o=c.createOscillator();o.type="sine";o.frequency.value=f*h;const g=c.createGain();const amp=hi?0.10:0.26;g.gain.setValueAtTime(0.0001,st);g.gain.exponentialRampToValueAtTime(amp,st+0.012);g.gain.exponentialRampToValueAtTime(0.0001,st+0.5);o.connect(g).connect(master);o.start(st);o.stop(st+0.52);});});
  const st=t+0.12,o=c.createOscillator();o.type="triangle";o.frequency.setValueAtTime(1200,st);o.frequency.exponentialRampToValueAtTime(2500,st+0.32);const g=c.createGain();g.gain.setValueAtTime(0.0001,st);g.gain.exponentialRampToValueAtTime(0.11,st+0.02);g.gain.exponentialRampToValueAtTime(0.0001,st+0.36);o.connect(g).connect(master);o.start(st);o.stop(st+0.37);}
export function critSfx(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator();o.type="square";o.frequency.setValueAtTime(880,t);o.frequency.exponentialRampToValueAtTime(1760,t+0.09);const g=c.createGain();g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.18,t+0.008);g.gain.exponentialRampToValueAtTime(0.0001,t+0.16);o.connect(g).connect(master);o.start(t);o.stop(t+0.17);}
export function chant(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const base=146.83;
  [[1,0.15],[1.5,0.08],[2,0.04]].forEach(([p,g])=>{const o=c.createOscillator();o.type="sine";o.frequency.value=base*p;const lfo=c.createOscillator();lfo.frequency.value=5.2;const lg=c.createGain();lg.gain.value=base*p*0.013;lfo.connect(lg).connect(o.frequency);const gg=c.createGain();gg.gain.setValueAtTime(0.0001,t);gg.gain.exponentialRampToValueAtTime(g,t+0.06);gg.gain.exponentialRampToValueAtTime(0.0001,t+0.5);o.connect(gg).connect(master);o.start(t);o.stop(t+0.52);lfo.start(t);lfo.stop(t+0.52);});}

// 煩悩陣営のグルーヴコンボ用。四つ打ちのキック。
export function grooveKick(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const o=c.createOscillator();o.type="sine";o.frequency.setValueAtTime(150,t);o.frequency.exponentialRampToValueAtTime(45,t+0.09);const g=c.createGain();g.gain.setValueAtTime(0.55,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.14);o.connect(g).connect(master);o.start(t);o.stop(t+0.15);}
// 煩悩陣営のグルーヴコンボ用。ハイハット(ノイズバッファ)。
export function grooveHat(open){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime,dur=open?0.09:0.03;const len=Math.floor(c.sampleRate*dur),nb=c.createBuffer(1,len,c.sampleRate),d=nb.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const ns=c.createBufferSource();ns.buffer=nb;const hp=c.createBiquadFilter();hp.type="highpass";hp.frequency.value=7000;const g=c.createGain();g.gain.setValueAtTime(0.22,t);g.gain.exponentialRampToValueAtTime(0.0001,t+dur);ns.connect(hp).connect(g).connect(master);ns.start(t);ns.stop(t+dur);}
// 煩悩陣営のグルーヴコンボ用。コンボが伸びるほど重なるシンセレイヤー。
export function grooveSynth(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;[220,277.18,329.63].forEach((f,i)=>{const o=c.createOscillator();o.type="sawtooth";o.frequency.value=f;const g=c.createGain();g.gain.setValueAtTime(0.0001,t);g.gain.exponentialRampToValueAtTime(0.05,t+0.02);g.gain.exponentialRampToValueAtTime(0.0001,t+0.22);o.connect(g).connect(master);o.start(t);o.stop(t+0.23);});}
// コンボ段階に応じてキック→ハイハット→シンセの順にレイヤーを重ねる。連打が乱れた際はscratch()で断ち切る。
export function grooveBeat(level){grooveKick();if(level>=4)grooveHat(level>=14);if(level>=14)grooveSynth();}
// 煩悩陣営のグルーヴコンボが途切れた際のスクラッチノイズ。
export function scratch(){if(state.s.muted)return;const c=ac();if(!c)return;const t=c.currentTime;const len=Math.floor(c.sampleRate*0.12),nb=c.createBuffer(1,len,c.sampleRate),d=nb.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const ns=c.createBufferSource();ns.buffer=nb;ns.playbackRate.setValueAtTime(2.4,t);ns.playbackRate.exponentialRampToValueAtTime(0.3,t+0.12);const bp=c.createBiquadFilter();bp.type="bandpass";bp.frequency.value=1500;bp.Q.value=3;const g=c.createGain();g.gain.setValueAtTime(0.3,t);g.gain.exponentialRampToValueAtTime(0.0001,t+0.12);ns.connect(bp).connect(g).connect(master);ns.start(t);ns.stop(t+0.12);}
